name: AIAssistant - Build and Push to Docker Hub

on:
  workflow_dispatch: # Allows manual trigger
  # push:
  #  branches:
  #    - master

env:
  IMAGE_NAME: sapydi/aiassistant-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          TAG=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::7}
          echo "Tagging image as $TAG and latest"
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest