name: AIAssistant - Build and Push to Docker Hub

on:
  workflow_dispatch: # manual trigger
  # push:
  #  branches:
  #    - master   # uncomment if you want auto-build on master

env:
  IMAGE_NAME: sapydi/aiassistant-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker image tag
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          TAG=$(date +%Y%m%d%H%M%S)-$SHORT_SHA
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        run: |
          echo "Building image with tag: $TAG"
          docker build \
            --build-arg GIT_SHA=$GITHUB_SHA \
            -t $IMAGE_NAME:$TAG \
            -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
